### ISSUE TITLE
[SUGGESTIONS] Block the Web analyzer

### ISSUE THREAD

**Issue by ViniDalvino** [syngp/snap#3]
- What is my suggestion : 
Not allowing to run the application if a web inspector software is Running. 
- Why should we add this :
If we add this, this would remove hability of game developper to grab the script with a web sniffer like fiddler.

*Side note : you are literally a big inspiration for me louka, I am so happy to hear that you are back in activity. I really love the fact that you beleive  in open source. Merci pour toute tes contribution.*

**Comment by recreationx** [comment]
This wouldn't be a problem if the script itself is properly obfuscated. The game developer will have trouble de-obfuscating the script even if he captured the script containing link.

**Comment by lingress** [comment]
Why bother blocking web-inspector software when the protocol itself is open source, and you can view the link to the script being executed in the UI?

**Comment by ViniDalvino** [comment]
@lingress I agree with you. let me close the issue.
